In [1]:
import numpy as np
import pandas as pd
from typing import Union, Literal

import keras
import tensorflow
import tensorflow as tf

import torch
from torch import nn
from torch.optim import Adam

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [3]:
!nvidia-smi

Sat May  2 17:14:24 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.15                 Driver Version: 581.15         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   42C    P8              2W /   70W |     400MiB /   8188MiB |      8%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
class DemoDataset:
    def __init__(self, model_type: Literal['tf', 'torch'] = 'tf'):
        self.model_type = model_type

        if self.model_type == 'tf':
            x = np.random.rand(2000, 3)
            y = x.sum(axis=1)
            self.data = tf.data.Dataset.from_tensor_slices((x, y)).batch(200)

        elif self.model_type == 'torch':
            x = torch.randn(2000, 3)
            y = x.sum(axis=1)
            dataset = torch.utils.data.TensorDataset(x, y)
            self.data = torch.utils.data.DataLoader(dataset, batch_size=200)

        else:
            raise ValueError("model_type must be 'tf' or 'torch'")

### Keras

In [5]:
dt = DemoDataset()
demo_data = dt.data

In [6]:
demo_data.take(3)

<_TakeDataset element_spec=(TensorSpec(shape=(None, 3), dtype=tf.float64, name=None), TensorSpec(shape=(None,), dtype=tf.float64, name=None))>

In [7]:
# next(iter(dt.data))

#### Building a keras subclassed model

Subclassed models are flexible — you can write arbitrary Python logic in `call()`.

Unlike `Functional API` models, a subclassed model does not inherently need to know the input shape (Unbuilt), and that’s one of the defining traits of a subclassed `tf.keras.Model`.

*For instance:* I can create a simple `MLP` layer without building it - An unbuilt Keras model is a model whose layers **do not yet have weights**, because the **model has never seen any `input shape`**.

In [8]:
@keras.saving.register_keras_serializable()
class DemoModelKeras(tf.keras.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.layer_1 = tf.keras.layers.Dense(100, activation='relu')
        self.layer_2 = tf.keras.layers.Dense(50, activation='relu')
        self.out_layer = tf.keras.layers.Dense(1)

    def call(self, x):
        x = self.layer_1(x)
        x = self.layer_2(x)
        return self.out_layer(x)    

In [9]:
tf_model = DemoModelKeras()

In [10]:
tf_model.summary()

Model: "demo_model_keras"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

#### Build the model - by feeding it sample data with expected input shape

In [11]:
tf_model(tf.zeros((1, 3)))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>

In [12]:
tf_model.summary()

Model: "demo_model_keras"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (1, 100)                    │             400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (1, 50)                     │           5,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (1, 1)                      │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,501 (21.49 KB)

 Trainable params: 5,501 (21.49 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
tf_model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [14]:
with tf.device('/GPU:0'):
    tf_model.fit(demo_data, epochs=10)

Epoch 1/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.3593 - mae: 1.4464  
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2831 - mae: 1.0463 
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4905 - mae: 0.6073 
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0813 - mae: 0.2299 
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0782 - mae: 0.2322 
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0481 - mae: 0.1795 
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0344 - mae: 0.1526 
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0296 - mae: 0.1412 
Epoch 9/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0245 - mae: 0.1294 
Epoch 10/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0220 - mae: 0.1223 


In [15]:
### save model
tf_model.save("./models/tf_model.keras", )

In [16]:
tf_loaded = tf.keras.models.load_model("./models/tf_model.keras")

In [17]:
dt = np.random.rand(1, 3)
p = tf_loaded(dt)

print(dt, '\n', p.numpy().item())

[[0.91274546 0.84853385 0.31970495]] 
 1.9478943347930908


### Torch

In [18]:
dt = DemoDataset(model_type='torch')
torch_data = dt.data

In [19]:
class DemoModelTorch(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_1 = nn.Linear(3, 100, device=device)
        self.layer_2 = nn.Linear(100, 50, device=device)
        self.out_layer = nn.Linear(50, 1, device=device)

    def forward(self, x):
        x = torch.relu(self.layer_1(x))
        x = torch.relu(self.layer_2(x))
        return self.out_layer(x)

In [20]:
torch_model = DemoModelTorch()

In [21]:
torch_model

DemoModelTorch(
  (layer_1): Linear(in_features=3, out_features=100, bias=True)
  (layer_2): Linear(in_features=100, out_features=50, bias=True)
  (out_layer): Linear(in_features=50, out_features=1, bias=True)
)

In [22]:
optimizer = Adam(torch_model.parameters(), lr=1e-3)

In [23]:
criterion = nn.MSELoss()

In [24]:
for epoch in range(10):
    for x, y in torch_data:
        x =  x.to(device)
        y = y.to(device)
        
        optimizer.zero_grad()
        preds = torch_model(x)
        loss = criterion(preds.squeeze(), y)
        loss.backward()
        optimizer.step()

    print(f"Epoch:{epoch}, loss: {loss.item():.3f}")

Epoch:0, loss: 2.267
Epoch:1, loss: 1.297
Epoch:2, loss: 0.442
Epoch:3, loss: 0.067
Epoch:4, loss: 0.066
Epoch:5, loss: 0.026
Epoch:6, loss: 0.019
Epoch:7, loss: 0.012
Epoch:8, loss: 0.008
Epoch:9, loss: 0.006


In [25]:
# save model
torch.save(torch_model, "./models/torch_model.pth")

In [26]:
# load torch model
loaded_torch = torch.load("./models/torch_model.pth", weights_only=False)

In [27]:
loaded_torch.eval()

DemoModelTorch(
  (layer_1): Linear(in_features=3, out_features=100, bias=True)
  (layer_2): Linear(in_features=100, out_features=50, bias=True)
  (out_layer): Linear(in_features=50, out_features=1, bias=True)
)

In [28]:
dt = torch.rand((1, 3), device=device)

with torch.no_grad():
    p = loaded_torch(dt)

    print(dt, '\n', p)

tensor([[0.3941, 0.2290, 0.8832]], device='cuda:0') 
 tensor([[1.5413]], device='cuda:0')
